Fix - perfomed code base linting

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -7,9 +7,7 @@ npx prettier --write ./frontend
 
 echo "Verify code clean up"
 
-npx eslint ./frontend
-
-if [ $? -ne 0 ]; then
-    echo "Some lint error still remain"
+if ! npx eslint ./frontend; then
+    echo "Lint errors remain. Commit aborted."
     exit 1
 fi
